# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: odoo19e
spec:
  selector:
    app: odoo19e
  ports:
    - protocol: TCP
      name: http
      port: 8069
      targetPort: 8069
    - protocol: TCP
      name: longpolling
      port: 8072
      targetPort: 8072
    - protocol: TCP
      name: jupyter
      port: 8888
      targetPort: 8888
  type: ClusterIP
