apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok-postgres
  template:
    metadata:
      labels:
        app: ngrok-postgres
    spec:
      containers:
      - name: ngrok
        image: ngrok/ngrok:alpine
        env:
        - name: NGROK_AUTHTOKEN
          valueFrom:
            secretKeyRef:
              name: ngrok-secret
              key: authtoken
        args:
          - "tcp"
          - "--log=stdout"
          - "postgres.default.svc.cluster.local:5432"
        ports:
        - containerPort: 4040
          name: dashboard