apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yml: |
    tunnel: 83a2e421-2b70-4ea3-a30e-705ea7bccf36

    ingress:
      # Evolution API - Manager interface
      - hostname: evolution.automateai.com.mx
        service: http://evolution.automateai.com.mx:8080
        originRequest:
          httpHostHeader: evolution.automateai.com.mx
          
      # n8n API - Manager interface
      - hostname: aut.automateai.com.mx
        service: http://aut.automateai.com.mx:5678
        originRequest:
          httpHostHeader: aut.automateai.com.mx

      - hostname: automateai.com.mx
        service: http://automateai.com.mx:8069
        originRequest:
          httpHostHeader: automateai.com.mx

      # ssh - Manager interface (CORREGIDO)
      - hostname: ssh.automateai.com.mx
        service: ssh://ssh.automateai.com.mx:22
      
      - hostname: diseño.rml-medica.com
        service: http://diseño.rml-medica.com:8069
        originRequest:
          httpHostHeader: diseño.rml-medica.com

      - hostname: note.automateai.com.mx
        service: http://note.automateai.com.mx:8069
        originRequest:
          httpHostHeader: note.automateai.com.mx

      # Postgres/TCP - (CORREGIDO)
      - hostname: tcp.automateai.com.mx
        service: tcp://tcp.automateai.com.mx:5432   

      - hostname: pgadmin.automateai.com.mx
        service: http://pgadmin.automateai.com.mx:8080
        originRequest:
          httpHostHeader: pgadmin.automateai.com.mx
          
      - hostname: rml-medica.com
        service: http://rml-medica.com:8089
        originRequest:
          httpHostHeader: rml-medica.com
      
      - hostname: jupyter.rml-medica.com
        service: http://jupyter.rml-medica.com:8888
        originRequest:
          httpHostHeader: jupyter.rml-medica.com

      - hostname: metabase.automateai.com.mx
        service: http://metabase.automateai.com.mx:30030
        originRequest:
          httpHostHeader: metabase.automateai.com.mx

      - hostname: odoo19.automateai.com.mx
        service: http://odoo19.automateai.com.mx:8069
        originRequest:
          httpHostHeader: odoo19.automateai.com.mx  

      - hostname: facturacion.rml-medica.com
        service: http://facturacion.rml-medica.com:5000
        originRequest:
          httpHostHeader: facturacion.rml-medica.com
      
      - service: http_status:404
